### ISSUE TITLE
when rotate to 90/180/270 deg, resize bug. Similar to #235

### ISSUE THREAD

**Issue by xueerli** [daybrush/moveable#333]
## Environments
* Framework name: react
* Framework version: 16.13.1
* Moveable Component version: "react-moveable": "^0.22.5"
* Testable Address(optional): [demo](https://codesandbox.io/s/infallible-noyce-pc377?file=/src/App.js:1260-1266)

## Description

there are two questions:
1. first resize to 90 / 180 / 270 deg, then resize , the width and height is incorrect.
![q1](https://ftp.bmp.ovh/imgs/2020/10/6814471187c401de.gif)
2. when resize to min size(width or height is zero), can not resize larger after.
![q2](https://ftp.bmp.ovh/imgs/2020/10/b1869575a7f16ee3.gif)

I referenced to #235, but my version is higher. Look forward to your reply, thanks.
code: <https://codesandbox.io/s/infallible-noyce-pc377?file=/src/App.js:1260-1266>

**Comment by daybrush** [comment]
@lixue007 

I checked. This behavior is probably normal. If the rotate is not exactly 90/180 / 270, the above phenomenon will occur if not more than 5px apart from the line by snap.

**Comment by daybrush** [comment]
@lixue007 

Let me check the second problem.

**Comment by lixue007** [comment]
Why the behavior in the first problem is normal? When rotate nearly 90/180/270, it will not be able to resize or become bigger or smaller suddenly.
![GitHub](https://ftp.bmp.ovh/imgs/2020/10/0b1ea38141d34766.gif)

**Comment by lixue007** [comment]
![demo](https://ftp.bmp.ovh/imgs/2020/10/532be9d8aef9cdf4.gif)

**Comment by daybrush** [comment]
@xueerli 


test `react-moveable@0.23.0-rc3`. (react-moveable@beta)

If it works, i will release it as a new version.

**Comment by xueerli** [comment]
@daybrush  The first problem is solves, thanks. But the second problem still has a little bug. When it resizes to zero for the first time it cannot be changed to zero, but for the second time it‘s can.
Please see the demo.
![demo](https://ftp.bmp.ovh/imgs/2020/10/71e58bf871d4c911.gif)

**Comment by daybrush** [comment]
@xueerli

test react-moveable@0.23.0-rc4. (react-moveable@beta)

Fixed a problem with zero size. Check if it works well.

If it works, i will release it as a new version.

**Comment by xueerli** [comment]
@daybrush 
Thanks for replying so quickly, but this problem still exists. Same as the gif above.

**Comment by daybrush** [comment]
@xueerli 

0.23.0 is released. Check it again.

**Comment by daybrush** [comment]
@xueerli 
https://github.com/daybrush/moveable/issues/332
This problem is also resolved, so check it again.

**Comment by xueerli** [comment]
@daybrush 
I had to update to 0.23.0, and re-run my project. But the problem with zero size and #332 are still  exists. Can you provide some demos?
Both of these problems are in this video.
![demo](https://ftp.bmp.ovh/imgs/2020/10/8589e0a0c5858fc5.gif)

**Comment by daybrush** [comment]
@xueerli 

https://codesandbox.io/s/zen-bush-9054y?file=/src/App.js

**Comment by xueerli** [comment]
@daybrush 
The problem with zero size is resolved in your demo, but it still exists in my project. I will check my code.
The other problem i replied to you in #332.
Thanks.
