### ISSUE TITLE
When the Target "Text" is in editable mode then movable not work.

### ISSUE THREAD

**Issue by AkashTvu** [daybrush/moveable#896]
## Environments
* Framework name: vue js
* Framework version: vue 2.0
* Moveable Component version: ^2.0.0-beta.2
* Testable Address(optional):

## Description
I have a target div and there is a text and when i edit this text by contentEditable="true" then "Movable" draging not work.

**Comment by AishwaryaMurade** [comment]
Same issue with me

**Comment by daybrush** [comment]
@AkashTvu 


* `croact-moveable` 0.3.1
* `@moveable/helper` 0.1.2
* `lit-moveable` 0.24.0
* `moveable` 0.47.1
* `preact-moveable` 0.49.1
* `react-moveable` 0.50.1
* `svelte-moveable` 0.39.1
* `vue-moveable` 2.0.0-beta.67
* `vue3-moveable` 0.22.1
* `ngx-moveable` 0.44.1



moveable's new version is released. 

`dragFocusedInput` prop is added. Try set `dragFocusedInput` to true.

**Comment by AkashTvu** [comment]
@daybrush I tried to use with vue-movable but still not working.

**Comment by daybrush** [comment]
@AkashTvu 


Here is the example code. Dragging is possible even when the input is focused.


https://codesandbox.io/s/serverless-cdn-w53j2t?file=/src/App.vue

**Comment by AkashTvu** [comment]
@daybrush I am not able to open the above link of codesanbox code. Please help

**Comment by daybrush** [comment]
@AkashTvu 

Oh sorry. changed to public.

https://codesandbox.io/s/serverless-cdn-w53j2t?file=/src/App.vue

**Comment by AkashTvu** [comment]
@daybrush I saw the code but  still there is two problems:
1. Unable to type in input box.
2. As is mentioned in the issue description we are using a div with  contentEditable="true" not an input box

Description : "_I have a target div and there is a text and when i edit this text by contentEditable="true" then "Movable" draging not work._"

**Comment by daybrush** [comment]
@AkashTvu 

moveable's new version is released. Issues 1 and 2 were resolved. Check it again.

**Comment by AkashTvu** [comment]
@daybrush Still not able to see fix. unable to edit and typing  the Input box.

**Comment by AishwaryaMurade** [comment]
Hi @daybrush can you please share the example code with fix for this issue? It will be helpful.

**Comment by daybrush** [comment]
@AkashTvu @AishwaryaMurade 

moveable's new version is released.
Codesandbox has also been updated.


https://codesandbox.io/s/serverless-cdn-w53j2t?file=/src/App.vue


See example (other frameworks):

https://daybrush.com/moveable/storybook/?path=/story/options--options-drag-focused-input

**Comment by AkashTvu** [comment]
https://user-images.githubusercontent.com/69041155/236893627-9f6c98f9-a0bb-43d3-af68-ec66d449a352.mp4

See still i am not able to type anything in inputbox

**Comment by daybrush** [comment]
@AkashTvu 

1. `checkInput: true` disables moveable on input.
2. `dragFocusedInput: true` activates moveable on the focused input.
3. `checkInput: false, dragFcousedInput: false` enable on input, disable on focused input.

**Comment by AkashTvu** [comment]
@daybrush I tried this props with my code and found still some problem that on first time page load it is editing perfectly but when i moved the text then i could not edit the text again.

https://user-images.githubusercontent.com/69041155/237027078-1d221f1d-4b62-4c85-a956-53d1e3efe272.mp4

**Comment by jadiagaurang** [comment]
@daybrush I am using Selecto to select Moveable Targets for my implementation!

I have used following config for the MoveableRef.

```javascript
var MoveableRef = new Moveable(me.canvasContainer, {
	target: [],

	// To Move
	draggable: true,

	// For contenteditable="true"
	checkInput: false,
	// https://github.com/daybrush/moveable/issues/896
	dragFocusedInput: false
});
```

How should I implement `e.isDouble` check for the selection event on the `contenteditable` Target.

I would like to allow the Users to Drag an element on the first click. If user click again on the selected element then allow them to edit the text.

Here is my Selecto Ref and Event Binding.

```javascript
var SelectoRef = new Selecto({
	container: me.canvasContainer,
	dragContainer: me.canvasContainer,
	selectableTargets: [".el-wrapper"],
	hitRate: 100,
	selectByClick: true,
	preventClickEventOnDrag: true,  //  Prevent click event on drag. (mousemove, touchmove)
	selectFromInside: false,
	toggleContinueSelect: ["shift"],
	ratio: 0
});
```

```javascript
SelectoRef.on("dragStart", function (event) {
	console.log("isDouble", event.isDouble);

	var target = event.inputEvent.target;

	if (
		me.objMoveable.isMoveableElement(target)
		|| me.targets.some(t => t === target
		|| t.contains(target))
		|| target.tagName === "BUTTON"
		//|| target.isContentEditable
	) {
		event.stop();
	}
}).on("select", function (event) {
	console.log("isDouble", event.isDouble);

	me.targets = event.selected;
	me.objMoveable.target = me.targets;
}).on("selectEnd", function (event) {
	console.log("isDouble", event.isDouble);

	if (event.isDragStart) {
		event.inputEvent.preventDefault();

		setTimeout(() => {
			me.objMoveable.dragStart(event.inputEvent);
		});
	}
});
```

**Comment by jadiagaurang** [comment]
Hi @daybrush 

Can you help me with my previous question?

For contentEditable Texts, I would like to allow the Users to Drag an element on the first click. If user click again on the selected element then allow them to edit the text.

I have provided my Moveable and Selecto config in the previous comment!

Can you help with the implementation on this idea?
